name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Fetch latest data
      env:
        PAGE_VIEWS_IGNORE: ${{ secrets.PAGE_VIEWS_IGNORE }}
      run: |-
        python3.10 -m pip install poetry
        python3.10 -m poetry install
        python3.10 -m poetry run python main.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git pull --rebase
        git push
