name: Generate views.csv

on:
  # push:
  workflow_dispatch:
  schedule:
  - cron:  '5 */12 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Fetch latest data
      run: |-
        python3.11 -m pip install poetry
        python3.11 -m poetry install
        python3.11 -m poetry run python views.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest views.csv: ${timestamp}" || exit 0
        git pull --rebase
        git push
